### ISSUE TITLE
Distinguish SCALE from CORE and FreeNAS

### ISSUE THREAD

**Issue by datamattsson** [hpe-storage/truenas-csp#39]
There's been an API change in the SCALE API which renders the CSP moot.

```
Sat, 07 Jan 2023 00:10:50 +0000 backend DEBUG TrueNAS POST request URI: iscsi/initiator
Sat, 07 Jan 2023 00:10:50 +0000 backend DEBUG TrueNAS request: {'comment': '4ffb98ef-36c4-c1e0-8a28-1ff9d9978391', 'initiators': ['iqn.2004-10.com.ubuntu:01:da65d25468d0'], 'auth_network': ['192.168.1.194/24', '192.168.10.167/24', '192.168.20.168/24', '172.29.43.192/32']}
Sat, 07 Jan 2023 00:10:50 +0000 backend DEBUG TrueNAS response: {'iscsi_initiator_create.auth_network': [{'message': 'Field was not expected', 'errno': 22}]}
Sat, 07 Jan 2023 00:10:50 +0000 backend ERROR Backend Request (POST) Exception: Traceback (most recent call last):
  File "/app/backend.py", line 266, in post
    self.req_backend.raise_for_status()
  File "/usr/lib/python3.10/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 422 Client Error: Unprocessable Entity for url: https://192.168.1.135/api/v2.0/iscsi/initiator
```

**Comment by datamattsson** [comment]
auth_network has moved from the initiator to the target in TrueNAS SCALE.
