### ISSUE TITLE
Fails to provision iscsi volumes on truenas scale

### ISSUE THREAD

**Issue by jstewart612** [hpe-storage/truenas-csp#67]
ElectricEel-24.10-RC.2

```
Tue, 22 Oct 2024 22:44:13 +0000 backend DEBUG TrueNAS GET Request through fetch: 504
Tue, 22 Oct 2024 22:44:13 +0000 backend ERROR Not found: Volume with name pvc-7ec72f22-d747-4813-9027-72f25459836c not found.
Tue, 22 Oct 2024 22:44:13 +0000 backend DEBUG Falcon Response (to HPE CSI): 404 Not Found
Tue, 22 Oct 2024 22:44:13 +0000 backend DEBUG Last backend requests Response: 504 Gateway Time-out
Tue, 22 Oct 2024 22:44:13 +0000 backend DEBUG API Key detected. Will use token authentication.
Tue, 22 Oct 2024 22:44:13 +0000 backend DEBUG TrueNAS GET request URI: core/ping
Tue, 22 Oct 2024 22:44:13 +0000 backend DEBUG TrueNAS response: "pong"
Tue, 22 Oct 2024 22:44:13 +0000 backend DEBUG API fetch caught 1 item
Tue, 22 Oct 2024 22:44:13 +0000 backend DEBUG HPE CSI Request <==============================>
Tue, 22 Oct 2024 22:44:13 +0000 backend DEBUG          uri: http://truenas-csp-svc:8080/containers/v1/volumes?name=pvc-b59d2d9e-29f4-47b3-9757-0299fca39228
Tue, 22 Oct 2024 22:44:13 +0000 backend DEBUG         body: None
Tue, 22 Oct 2024 22:44:13 +0000 backend DEBUG        query: name=pvc-b59d2d9e-29f4-47b3-9757-0299fca39228
Tue, 22 Oct 2024 22:44:13 +0000 backend DEBUG       method: GET
Tue, 22 Oct 2024 22:44:13 +0000 backend DEBUG content_type: application/json
Tue, 22 Oct 2024 22:44:13 +0000 backend DEBUG      headers: {"HOST": "truenas-csp-svc:8080", "USER-AGENT": "Go-http-client/1.1", "CONNECTION": "close", "ACCEPT": "
Tue, 22 Oct 2024 22:44:13 +0000 backend DEBUG API Key detected. Will use token authentication.
Tue, 22 Oct 2024 22:44:13 +0000 backend DEBUG TrueNAS GET request URI: pool/dataset
Tue, 22 Oct 2024 22:44:16 +0000 backend DEBUG TrueNAS response: <html>
<head><title>504 Gateway Time-out</title></head>
<body>
<center><h1>504 Gateway Time-out</h1></center>
<hr><center>nginx</center>
</body>
</html>
```

```
Tue, 22 Oct 2024 22:49:16 +0000 backend ERROR Backend Request (GET) Exception: Traceback (most recent call last):
  File "/app/backend.py", line 404, in get
    self.req_backend.raise_for_status()
  File "/app/lib/python3.12/site-packages/requests/models.py", line 1024, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 504 Server Error: Gateway Time-out for url: https://hl15-1.home.thecrimsontint.com/api/v2.0/pool/dataset
```

**Comment by jstewart612** [comment]
Proof that truenas-csp pod can hit the API:

```
/app # hostname; wget -q -O- https://hl15-1.home.thecrimsontint.com/api/v2.0 | head -n5
truenas-csp-dbc4f9d86-xg9xn
{
 "openapi": "3.0.0",
 "info": {
  "title": "TrueNAS RESTful API",
  "version": "v2.0"
/app #
```

**Comment by jstewart612** [comment]
If I had to guess, your problem is here:

https://github.com/hpe-storage/truenas-csp/issues/66#issuecomment-2408110774

If I manually run that API call, it takes about 25s to return.

**Comment by datamattsson** [comment]
> If I manually run that API call, it takes about 25s to return.

Thank you for reporting this. How many datasets (including snapshots) do you have?

**Comment by jstewart612** [comment]
About 20

**Comment by datamattsson** [comment]
I did some adhoc curl'ing. In the current shape and form, one second is added to `curl -s root:admin@truenas/api/v2.0/pool/dataset` for every 100 datasets. On my VM running on 10 year old hardware, 600 datasets took 5 seconds to GET.

Using the `query-filters` and dialing down `query-options` to just retrieve the bare minimum, the same GET takes 700ms and this is definitely the optimization I'm looking to do, but I think there's something else that is broken in your case.

**Comment by jstewart612** [comment]
Same truenas version?

**Comment by datamattsson** [comment]
Dragonfish-24.04.2

**Comment by jstewart612** [comment]
Ah.  I am ElectricEel-24.10-RC.2.

Also:  the entire way you do business will break in 25.04:

![image](https://github.com/user-attachments/assets/a068c319-2e69-4e97-b79f-1697ecdac703)

**Comment by jstewart612** [comment]
Seems this will be its replacement: https://github.com/truenas/api_client

**Comment by jstewart612** [comment]
That client performs the same api call in 17s.

**Comment by jstewart612** [comment]
Regardless... your hypothesis is overall correct.

I have two TrueNAS scale appliances.  One this RESTful API call works fine as is.  The other, it does not.  Happen to know where on a TrueNAS scale box the restful api logs?  Would be interesting to fully RCA this.

**Comment by jstewart612** [comment]
Runtime of RESTful call at localhost:

```
real    1m17.001s
user    0m0.004s
sys     0m0.033s
```

**Comment by jstewart612** [comment]
Indeed.  That, however, is an issue for iXSystems.  I'll file a ticket over there.

So it sounds like the path here is probably filters in a future release then websocket come 25.04 or maybe websocket first?

**Comment by datamattsson** [comment]
> So it sounds like the path here is probably filters in a future release then websocket come 25.04 or maybe websocket first?

The next release by the end of the year will have query option filters. This will most likely be the last RESTful release before switching to websocket but that has not been scoped yet.
